"""Add cost field to items

Revision ID: 839fff2a2af8
Revises: edcfc55efde8
Create Date: 2023-05-06 14:22:59.071000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839fff2a2af8'
down_revision = 'edcfc55efde8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('cost', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'cost')
    # ### end Alembic commands ###
